### ISSUE TITLE
[Bug]: Error on recreateOrder if one time token is used

### ISSUE THREAD

**Issue by MercuryKojo** [pimcore/ecommerce-framework-bundle#103]
### Expected behavior

order is recreated and containing the voucher token which is onetime use

### Actual behavior

recreate order reapplies the voucher token to the new order without removing it for the source order and throws an error, that the voucher can not be used anymore

### Steps to reproduce

add a onetime use voucher to the cart and start a payment
return and change cart so the order will be recreated
start payment again -> throws exception and the new order has not order items and no voucher

**Comment by kingjia90** [comment]
Is it reproducible on the Pimcore demo? 
I wasn't able to simulate, can you check if `usages` of the given token is still 0?

![image](https://github.com/pimcore/ecommerce-framework-bundle/assets/6014195/3353f5b2-14e6-465e-addf-fa47005fa926)
can you also provide the screenshot of the error message (stack trace or any code/error message)?

**Comment by MercuryKojo** [comment]
Hi @kingjia90 here is the Stacktrace:
[2023-03-18T09:57:04.352127+01:00] request.CRITICAL: Uncaught PHP Exception Pimcore\Bundle\EcommerceFrameworkBundle\Exception\VoucherServiceException: "Token has already been used." at /home/.../www/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php line 140 {"exception":"[object] (Pimcore\\Bundle\\EcommerceFrameworkBundle\\Exception\\VoucherServiceException(code: 1): Token has already been used. at /home/.../www/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php:140)"} []

[2023-03-18T09:57:04.352301+01:00] app.ERROR: Pimcore\Bundle\EcommerceFrameworkBundle\Exception\VoucherServiceException: Token has already been used. in /home/.../www/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php:140 Stack trace: 
#0 /home/.../www/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/VoucherService/DefaultService.php(136): Pimcore\Bundle\EcommerceFrameworkBundle\VoucherService\TokenManager\Pattern->applyToken('STUcard-AfWkb', Object(App\Ecommerce\CartManager\SessionCart), Object(App\Model\DataObject\OnlineShopOrder)) 
#1 /home/.../www/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php(744): Pimcore\Bundle\EcommerceFrameworkBundle\VoucherService\DefaultService->applyToken('STUcard-AfWkb', Object(App\Ecommerce\CartManager\SessionCart), Object(App\Model\DataObject\OnlineShopOrder)) 
#2 /home/.../www/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php(246): Pimcore\Bundle\EcommerceFrameworkBundle\OrderManager\V7\OrderManager->applyVoucherTokens(Object(App\Model\DataObject\OnlineShopOrder), Object(App\Ecommerce\CartManager\SessionCart)) #3 /home/.../www/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php(349): Pimcore\Bundle\EcommerceFrameworkBundle\OrderManager\V7\OrderManager->getOrCreateOrderFromCart(Object(App\Ecommerce\CartManager\SessionCart)) 
#4 /home/.../www/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CheckoutManager/V7/CheckoutManager.php(227): Pimcore\Bundle\EcommerceFrameworkBundle\OrderManager\V7\OrderManager->recreateOrder(Object(App\Ecommerce\CartManager\SessionCart)) 
#5 /home/.../www/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CheckoutManager/V7/CheckoutManager.php(247): Pimcore\Bundle\EcommerceFrameworkBundle\CheckoutManager\V7\CheckoutManager->checkIfPaymentIsPossible() 
#6 /home/.../www/src/Controller/PaymentController.php(72): Pimcore\Bundle\EcommerceFrameworkBundle\CheckoutManager\V7\CheckoutManager->initOrderPayment() 
#7 /home/.../www/vendor/symfony/http-kernel/HttpKernel.php(153): App\Controller\PaymentController->paymentAction(Object(Symfony\Component\HttpFoundation\Request), Object(Pimcore\Log\ApplicationLogger)) 
#8 /home/.../www/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) 
#9 /home/.../www/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /home/.../www/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) 
#11 {main} [] []


Pimcore Demo definitely throws an Error with this steps:

Configure Commercial voucher
![image](https://github.com/pimcore/ecommerce-framework-bundle/assets/12114276/d35ff7fd-8bb4-4a5b-9016-e9fe6e704a2b)
add commercial car and voucher
![image](https://github.com/pimcore/ecommerce-framework-bundle/assets/12114276/6c6a3a09-aa0a-4dda-ab27-cc8a51884c5c)
Checkout until payment and start creditcard payment (but don't complete the payment)
![image](https://github.com/pimcore/ecommerce-framework-bundle/assets/12114276/4268d1d0-03b6-47e6-b64c-f9cd30f4e76b)
Go Back to Cart and Change the amount to 2 (so pimcore will recreate the order)
![image](https://github.com/pimcore/ecommerce-framework-bundle/assets/12114276/b671580c-b211-45e4-afdd-3c51ceb5dce0)
checkout again until Payment select and click on creditcard again and it will throw an error:
![image](https://github.com/pimcore/ecommerce-framework-bundle/assets/12114276/71da7633-c7b5-4c25-b958-18d44ced7674)

**Comment by kingjia90** [comment]
Confirming the problem. 
When one step into the payment, in the backend it would create the order which logs the payment history and there the price is the already discounted as if it applied the voucher and triggers its usage. 
From user perspective, going back to change the cart should be naturally possible, but i am having some concern about concurrent same one-time vouchers on these pending orders, if we trigger usage only at successfull payments. 🤔 Need digging some more on how to fix this

**Comment by fashxp** [comment]
My thoughts on this: 
Finishing the original and the recreated order is most likely some unwanted scenario. It is possible though, and to make it traceable and also fixable for customer service we decided to do it that way and keeping both orders. 

From that perspective, I think most reasonable fix for that would be to remove the voucher from the original order when recreating the order (and place the information in notes or version notes for traceability)? 

@kingjia90 WDYT?

**Comment by kingjia90** [comment]
@fashxp had some time to look into it and seems that #121 may fix it

**Comment by dvesh3** [comment]
Fixed by #121
