### ISSUE TITLE
[Bug]: searchAttributes accessed before initialization

### ISSUE THREAD

**Issue by langert** [pimcore/ecommerce-framework-bundle#113]
### Expected behavior

building index without error

### Actual behavior

Error building index in v1.0.2 in pimcore 11.0.3

In AbstractConfig.php line 187:
                                                                                                                       
  Typed property Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Config\AbstractConfig::$searchAttributes must n  
  ot be accessed before initialization  

### Steps to reproduce

bin/console ecommerce:indexservice:bootstrap --create-or-update-index-structure

**Comment by j-jonas** [comment]
https://github.com/pimcore/ecommerce-framework-bundle/pull/114

**Comment by dvesh3** [comment]
Fixed by #115
