### ISSUE TITLE
[Bug]: SelectFromMultiSelect -> trim(null)

### ISSUE THREAD

**Issue by 80Quattro** [pimcore/ecommerce-framework-bundle#144]
### Expected behavior

SelectFromMultiSelect works also if $value == AbstractFilterType::EMPTY_STRING

### Actual behavior

trim(): Argument #1 ($string) must be of type string, null given

An Exception is thrown if $value == AbstractFilterType::EMPTY_STRING in SelectFromMultiSelect

SelectFromMultiSelect.php, line 66 -> There is assigned null to $value,

then, in line 72, function trim($value) is called -> trim(null) is not allowed in PHP: [doku](https://www.php.net/manual/en/function.trim.php)

### Steps to reproduce

-

**Comment by kingjia90** [comment]
Thank you!


Fixed by https://github.com/pimcore/ecommerce-framework-bundle/pull/145
