### ISSUE TITLE
[Bug]: Array to string conversion while product indexing 

### ISSUE THREAD

**Issue by 80Quattro** [pimcore/ecommerce-framework-bundle#150]
### Expected behavior

Product indexer works with all provided getters (also DefaultBrickGetterSequenceToMultiselect)

### Actual behavior

If in index_service configuration, the `getter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Getter\DefaultBrickGetterSequenceToMultiselect` is set, the exception is thrown:

> Exception in IndexService: ErrorException: Warning: Array to string conversion in /var/www/html/app/site/vendor/pimcore/ecommerce-framework-bundle/src/IndexService/Worker/AbstractWorker.php

The DefaultBrickGetterSequenceToMultiselect getter returns a multidimensional array, which cannot be processed in implode() function in AbstractWorker->convertArray()

### Steps to reproduce

- Set `getter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Getter\DefaultBrickGetterSequenceToMultiselect` in index_service configuration
- Run indexer

**Comment by fashxp** [comment]
fixed via  #167
