### ISSUE TITLE
[Task]: Check usages of `Pimcore\Db\Helper::insertOrUpdate` and `ON DUPLICATE KEY`

### ISSUE THREAD

**Issue by mcop1** [pimcore/ecommerce-framework-bundle#19]
### Improvement description
Follow up to https://github.com/pimcore/pimcore/issues/13507

Check for usages of `Pimcore\Db\Helper::insertOrUpdate` and `ON DUPLICATE KEY` again, e.g.
https://github.com/pimcore/pimcore/issues/14408

**Comment by Corepex** [comment]
found one `insertOrUpdate` here: https://github.com/pimcore/pimcore/blob/601966ecd2cc7da9752cf87b63febae1c6bb16be/bundles/EcommerceFrameworkBundle/src/IndexService/Worker/Helper/MySql.php#L72

**Comment by mcop1** [comment]
Issue was transferred from core repository, since the only left occurrence is in the ecom-framework
