### ISSUE TITLE
[Bug]: Bundle "PimcoreEcommerceFrameworkBundle" does not exist or it is not enabled. Maybe you forgot to add it in the "registerBundles()" method of your "App\Kernel.php" file?

### ISSUE THREAD

**Issue by decode-factory** [pimcore/ecommerce-framework-bundle#204]
### Expected behavior

On hitting the command `php bin/console pimcore:bundle:install PimcoreEcommerceFrameworkBundle` it must install the `PimcoreEcommerceFrameworkBundle` easily and must configure automatically. I am facing issue in both installation. While using 
`composer require pimcore/ecommerce-framework-bundle` I am facing another issue. Both issues are attached below

### Actual behavior

![image](https://github.com/user-attachments/assets/a7acf1fc-b257-43da-a885-dee29cc028e8)

![image](https://github.com/user-attachments/assets/12ca04eb-0c80-4f21-a2ad-98c4b76ab6cf)

### Steps to reproduce

Install pimcore/skeletion project and navigate into the docker container and start installation

**Comment by jdreesen** [comment]
But you *did* add the bundle to your `config/bundles.php` file or `Kernel::registerBundles()` method before running the command?

**Comment by decode-factory** [comment]
@jdreesen now it is working. Thanks for the help!!!!!!
