### ISSUE TITLE
[Bug]: search for 'blue' results in server error

### ISSUE THREAD

**Issue by heigpa** [pimcore/ecommerce-framework-bundle#209]
### Expected behavior

- Results for search with search-term 'blue' are shown

### Actual behavior

- Server error 500

![Image](https://github.com/user-attachments/assets/0b255a1a-dd60-409f-84f3-39145a87e78f)

### Steps to reproduce

- Login to QA as admin
- Open a product
- Open the shop via the show menu entry
- Open the search on the top right
- Search for 'blue'

**Comment by mattamon** [comment]
Fixed on QA since QA used wrong Tenant.
