### ISSUE TITLE
[Bug]: empty 'pre select' field for filter 'MultiSelect from MultiSelect'

### ISSUE THREAD

**Issue by heigpa** [pimcore/ecommerce-framework-bundle#210]
### Expected behavior

- Color options should be shown in the field 'Pre Select'

### Actual behavior

- Pre select field is empty
![Image](https://github.com/user-attachments/assets/90f68ea2-643a-43f8-a9ef-aebc17910b19)

### Steps to reproduce

- Login as admin
- Open filter 'commercial-cars'
- Open the 'Filters' tab
- Go to the 'MultiSelect from MultiSelect' filter
- Select 'OpenSearch' and 'color' for the field values

- Environment: QA

**Comment by mattamon** [comment]
Fixed with https://github.com/pimcore/ecommerce-framework-bundle/pull/208/commits/fd32d0cb44f6543ca02cc5f2539810d8b1287e76
