### ISSUE TITLE
[Bug]: symfony/twig-bridge v6.2.8 conflicts with symfony/form v6.2.0

### ISSUE THREAD

**Issue by Rickard-SGN** [pimcore/ecommerce-framework-bundle#71]
### Expected behavior

ecommerce-framework-bundle would be installed

### Actual behavior

symfony/twig-bridge v6.2.8 conflicts with symfony/form v6.2.0

symfony/twig-bridge requires "symfony/form": "^6.2.7"

### Steps to reproduce

composer require pimcore/ecommerce-framework-bundle

**Comment by dvesh3** [comment]
fixed with https://github.com/pimcore/ecommerce-framework-bundle/commit/a2720cdbed162346ac94e2dc3bba2008f14ca6f6
