### ISSUE TITLE
[Bug][Ecommerce]: custom pricing rule class not applied on listings

### ISSUE THREAD

**Issue by jremmurd** [pimcore/ecommerce-framework-bundle#74]
### Expected behavior

Custom pricing rule class gets applied.

### Actual behavior

Custom pricing rule class is not used in listings. 

Workaround:

![image](https://user-images.githubusercontent.com/9052094/174999167-51b38820-7fd8-4ab2-9604-de1850b70290.png)

### Steps to reproduce

Configure custom pricing rule class
![image](https://user-images.githubusercontent.com/9052094/175000866-022496da-6c99-4a41-ab6b-947949e46d32.png)

Use pricing rule class
```
$list = new App\Ecommerce\PricingManager\Rule\Listing();
$list->current()?->myCustomMethod(); // should not throw an error but does
```

**Comment by robertSt7** [comment]
Read symfony config `rule_class`  and insert the value [there](https://github.com/pimcore/ecommerce-framework-bundle/blob/4c2f9f5f20d128a1f61ef0a5335516c0a8cba1c5/src/PricingManager/Rule/Listing/Dao.php#L27)

**Comment by robertSt7** [comment]
Hi @jremmurd we can't use the `rule_class` out of the symfony config, because the actual `tenant` is defined by the `PricingManager` and the `Listing` should be for all `Rules`. If you want to use the `Listing` directly your Workaround is the way to go, otherwise please use the `PricingManger`.

**Comment by robertSt7** [comment]
Closed due to the previous comment
